### ISSUE TITLE
[enhancement] - Insert and recollect simulation metadata

### ISSUE THREAD

**Issue by Radiation-Transport** [JADE-V-V/JADE-RAW-RESULTS#1]
Add simulation metadata once available from JADE engine: https://github.com/JADE-V-V/JADE/issues/281.

Tasks to perform:

- [x] Insert simulation metadata for previous cases: create it manually 
- [ ] Insert simulation metadata for future JADE cases: create it automatically
- [x] collect metadata in a dedicated table/dataframe to have an overview of the simulation performed per code.

**Comment by dodu94** [comment]
the automatic creation depends on JADE, manual and visualization has been added here already
